# Generated by Django 5.2 on 2026-09-09 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_study_layer', 'Can view the private learning study layer')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('goal', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('vault_folder', models.CharField(blank=True, max_length=500)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('module', 'Module'), ('concept', 'Concept'), ('source', 'Source')], max_length=20)),
                ('slug', models.SlugField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('vault_filename', models.CharField(max_length=200)),
                ('body_markdown', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True, null=True)),
                ('part', models.CharField(blank=True, max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('vault_modified', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concepts', to='learning.note')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='learning.learningpath')),
            ],
            options={
                'ordering': ['kind', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StudyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('study', 'Study'), ('question', 'Question')], max_length=20)),
                ('text', models.TextField()),
                ('text_hash', models.CharField(db_index=True, max_length=64)),
                ('order', models.PositiveIntegerField(default=0)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='learning.note')),
            ],
            options={
                'ordering': ['note', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('leaf', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='learning.learningpath')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='notes', to='learning.tag'),
        ),
        migrations.CreateModel(
            name='TaskState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_hash', models.CharField(max_length=64)),
                ('done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_states', to='learning.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_task_states', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_markdown', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notes', to='learning.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_target', models.CharField(max_length=200)),
                ('display_text', models.CharField(blank=True, max_length=200)),
                ('from_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_out', to='learning.note')),
                ('to_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links_in', to='learning.note')),
            ],
            options={
                'ordering': ['raw_target'],
                'indexes': [models.Index(fields=['to_note'], name='learning_no_to_note_011b8f_idx'), models.Index(fields=['from_note', 'raw_target'], name='learning_no_from_no_b122c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='NoteStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not-started', 'Not started'), ('reading', 'Reading'), ('review', 'Review'), ('done', 'Done')], default='not-started', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='learning.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'note statuses',
                'constraints': [models.UniqueConstraint(fields=('user', 'note'), name='uniq_status_per_user_note')],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('answered', 'Answered')], default='open', max_length=20)),
                ('answer', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='learning_qu_user_id_910b4a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('path', 'name'), name='uniq_tag_name_per_path'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['path', 'kind'], name='learning_no_path_id_ae8cbc_idx'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(fields=('path', 'vault_filename'), name='uniq_note_vault_filename_per_path'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(fields=('path', 'slug'), name='uniq_note_slug_per_path'),
        ),
        migrations.AddIndex(
            model_name='taskstate',
            index=models.Index(fields=['user', 'done'], name='learning_ta_user_id_bf9d7a_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskstate',
            constraint=models.UniqueConstraint(fields=('user', 'note', 'text_hash'), name='uniq_taskstate_per_user_note_hash'),
        ),
        migrations.AddConstraint(
            model_name='usernote',
            constraint=models.UniqueConstraint(fields=('user', 'note'), name='uniq_usernote_per_user_note'),
        ),
    ]
