# Generated by Django 5.2 on 2026-09-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='moc_filename',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
