# Generated by Django 5.2 on 2026-08-10 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True)),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_token_fingerprint', models.CharField(blank=True, max_length=32)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.TextField(blank=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Spotify auth',
                'verbose_name_plural': 'Spotify auth',
            },
        ),
        migrations.CreateModel(
            name='ListeningItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=64, unique=True)),
                ('item_type', models.CharField(choices=[('track', 'Song'), ('episode', 'Podcast episode')], max_length=16)),
                ('name', models.CharField(max_length=500)),
                ('creator_name', models.CharField(blank=True, max_length=500)),
                ('show_name', models.CharField(blank=True, max_length=500)),
                ('show_spotify_id', models.CharField(blank=True, max_length=64)),
                ('duration_ms', models.BigIntegerField(blank=True, null=True)),
                ('spotify_url', models.URLField(blank=True, max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('first_played_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_played_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('observation_count', models.PositiveIntegerField(default=0)),
                ('max_progress_ms', models.BigIntegerField(blank=True, null=True)),
                ('fully_played', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_played_at', 'name'],
                'indexes': [models.Index(fields=['item_type', '-last_played_at'], name='listening_l_item_ty_abfae8_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(db_index=True)),
                ('source', models.CharField(choices=[('recently_played', 'Recently played (history)'), ('currently_playing', 'Currently playing (poll)')], max_length=32)),
                ('progress_ms', models.BigIntegerField(blank=True, null=True)),
                ('resume_position_ms', models.BigIntegerField(blank=True, null=True)),
                ('fully_played', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_events', to='listening.listeningitem')),
            ],
            options={
                'ordering': ['-played_at'],
                'indexes': [models.Index(fields=['source', '-played_at'], name='listening_p_source_d61681_idx')],
                'constraints': [models.UniqueConstraint(fields=('item', 'played_at', 'source'), name='unique_play_observation')],
            },
        ),
    ]
