# Generated by Django 5.2 on 2026-08-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_dashboard', 'Can view the listening dashboard')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
