"""
Django settings for Website project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from a local .env file (repo root) if present.
# In production, systemd injects the real env vars and there is no .env, so
# this is simply a no-op there. Values already set in the environment win.
load_dotenv(BASE_DIR.parent / ".env")


def env_bool(name, default=False):
    """Read a boolean-ish environment variable ("1", "true", "yes", "on")."""
    return os.environ.get(name, str(default)).strip().lower() in ("1", "true", "yes", "on")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False (secure by default). Local dev opts in via DJANGO_DEBUG=True in .env.
# Read BEFORE the secret key, because it decides whether a missing key is fatal.
DEBUG = env_bool("DJANGO_DEBUG", False)

# SECURITY WARNING: keep the secret key used in production secret!
#
# The literal below is published — this repo is public, and it additionally sits
# in git history from before the settings were env-driven. That is acceptable
# ONLY because it never signs anything outside local development.
#
# Django signs session cookies and password-reset tokens with this key, so a
# production process falling back to a published value would let anyone forge an
# admin session without touching a password. The guard below makes that
# impossible rather than merely unlikely: with DEBUG off and no SECRET_KEY in the
# environment, the process refuses to start instead of silently running insecure.
# Failing loudly at boot is the whole point — the previous arrangement failed
# OPEN, and a deploy that dropped the variable would have looked perfectly normal.
DEV_ONLY_SECRET_KEY = "django-insecure-*^60)mnxs*pik%4jx1i(1f2$hizts1s*p#8318)&yhy14g8ab8"

SECRET_KEY = os.environ.get("SECRET_KEY", "")
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            "SECRET_KEY is not set. Refusing to start with the development key, "
            "which is published in this repo's public history — using it would "
            "make every session cookie and password-reset token forgeable.\n"
            "Set SECRET_KEY in /etc/anotiontoponder.env (generate one with: "
            "python -c \"from django.core.management.utils import "
            "get_random_secret_key; print(get_random_secret_key())\")."
        )
    SECRET_KEY = DEV_ONLY_SECRET_KEY

# Hosts/domains this site is allowed to serve. Required once DEBUG is False.
# Comma-separated in DJANGO_ALLOWED_HOSTS; in local dev (DEBUG on) fall back to localhost.
ALLOWED_HOSTS = [h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()]
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["127.0.0.1", "localhost"]


# Application definition

INSTALLED_APPS = [
    'blog', #make django aware of our app: blog
    'listening', # private Spotify listening tracker (see the Spotify Listening Tracker scope)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'blog.middleware.PageAccessLogMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates"
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Website.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Local dev stays on SQLite with zero configuration. Production sets DB_ENGINE=mysql
# (plus the DB_* vars) to switch engines without any code change.
if os.environ.get("DB_ENGINE") == "mysql":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ['DB_NAME'],
            'USER': os.environ['DB_USER'],
            'PASSWORD': os.environ['DB_PASSWORD'],
            'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
            'PORT': os.environ.get('DB_PORT', '3306'),
            'OPTIONS': {'charset': 'utf8mb4'},
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Source static files (checked into the repo, served by runserver in dev).
STATICFILES_DIRS = [
    BASE_DIR / "static"
]

# Destination `collectstatic` gathers everything into for production; Nginx
# serves this directory directly. Kept separate from STATICFILES_DIRS above.
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"

# Resume page gate. The resume view reads these via getattr(settings, ...);
# defining them here from the environment makes them configurable (dev fallbacks).
RESUME_ACCESS_PASSWORD = os.environ.get("RESUME_ACCESS_PASSWORD", "viewresumeonwebsite")
RESUME_REQUEST_EMAIL = os.environ.get("RESUME_REQUEST_EMAIL", "hello@example.com")

# Spotify listening tracker (see the "Spotify Listening Tracker" scope).
# The refresh token is the durable credential; the one-time browser authorization
# happens LOCALLY, so the server never needs a redirect URI.
SPOTIFY_CLIENT_ID = os.environ.get("SPOTIFY_CLIENT_ID", "")
SPOTIFY_CLIENT_SECRET = os.environ.get("SPOTIFY_CLIENT_SECRET", "")
SPOTIFY_REFRESH_TOKEN = os.environ.get("SPOTIFY_REFRESH_TOKEN", "")
# Must match the dashboard registration byte-for-byte. Spotify prohibits
# "localhost" — loopback has to be an explicit IP literal.
SPOTIFY_REDIRECT_URI = os.environ.get("SPOTIFY_REDIRECT_URI", "http://127.0.0.1:8888/callback")

# CSRF trust for the production HTTPS domain(s) — required for admin/comment POSTs.
# Comma-separated full origins, e.g. "https://anotiontoponder.com,https://www.anotiontoponder.com".
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()
]

# Production-only security hardening. Gated on DEBUG so local HTTP dev is unaffected.
if not DEBUG:
    # We terminate TLS at Nginx/Cloudflare and proxy plain HTTP to Django on localhost.
    # This tells Django to treat requests as secure when the proxy sets X-Forwarded-Proto=https,
    # preventing an infinite redirect loop with SECURE_SSL_REDIRECT. Safe only behind a trusted proxy.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True          # send any HTTP request to HTTPS
    SESSION_COOKIE_SECURE = True        # session cookie only over HTTPS
    CSRF_COOKIE_SECURE = True           # CSRF cookie only over HTTPS
    SECURE_CONTENT_TYPE_NOSNIFF = True  # block MIME-type sniffing
    # HSTS: tell browsers to use HTTPS only. Sticky — start small (1 hour), raise
    # to a year + add `preload` once HTTPS is proven stable.
    SECURE_HSTS_SECONDS = 3600
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
