# Generated by Django 5.2 on 2026-05-31 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_seed_initial_blog_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover_upload',
            field=models.ImageField(blank=True, upload_to='blog/covers/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/content/%Y/%m/')),
                ('reference_name', models.CharField(max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_images', to='blog.poem')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_images', to='blog.blogpost')),
            ],
            options={
                'ordering': ['reference_name', '-created_at'],
            },
        ),
    ]
