# Generated by Django 5.2 on 2026-07-15 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_cover_upload_contentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='related_musing_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_poems', to='blog.blogpost'),
        ),
    ]
